export const StaffFields = [
  {
    name: "firstName",
    label: "اسم کارمند ",
    type: "text",
    required: true,
    maxLength: 100,
    placeholder: "اسم کارمند",
  },
  {
    name: "lastName",
    label: "تخلص ",
    type: "text",
    required: true,
    maxLength: 100,
    placeholder: "تخلص کارمند ",
  },
  {
    name: "hireDate",
    label: " تاریخ مقرر",
    type: "date",
  },
  {
    name: "position",
    label: "بست",
    type: "text",
    required: true,
    maxLength: 100,
    placeholder: "بست ",
  },
  {
    name: "salary",
    label: " معاش",
    type: "number",
    required: true,
    maxLength: 100,
    placeholder: " معاش",
  },
  {
    name: "prepayment",
    label: " پیش پرداخت",
    type: "text",
    maxLength: 100,
    placeholder: " پیش پرداخت ",
  },
   {
    name: "address",
    label: "ادرس  *",
    type: "text",
    required: true,
    maxLength: 100,
    placeholder: "ادرس ",
  },
  {
    name: "phone",
    label: "شماره تماس اصلی",
    type: "text",
    required: true,
    maxLength: 20,
    placeholder: "07xxxxxxxx",
  },
  {
    name: "familyPhone1",
    label: " شماره تماس فامیلی اول",
    type: "text",
    maxLength: 20,
    placeholder: "اختیاری",
  },
  {
    name: "familyPhone2",
    label: " شماره تماس فامیلی دوهم",
    type: "text",
    maxLength: 20,
    placeholder: "اختیاری",
  },

  {
    name: "contractFileUpload",
    label: "فایل قرارداد",
    type: "file",
    placeholder: "pdf, jpg, png",
  },
  {
    name: "fileType",
    label: "نوعیت فایل",
    type: "select",
    options: [
      { value: "pdf", label: "PDF" },
      { value: "jpg", label: "JPG" },
      { value: "png", label: "PNG" },
      { value: "docx", label: "DOCX" },
    ],
    placeholder: "نوعیت فایل را انتخاب کنید",
  },
  {
    name: "photoFile",
    label: "تصویر",
    type: "file",
    placeholder: "تصویر",
  },
];
