// <auto-generated />
using System;
using DMS.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DMSAPI.Migrations
{
    [DbContext(typeof(DMSContext))]
    [Migration("20260717171954_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("StaffId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Appointments.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("apt_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("details");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount");

                    b.Property<int>("Installment")
                        .HasColumnType("INTEGER")
                        .HasColumnName("installment");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MeetDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("meet_date");

                    b.Property<string>("Notification")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("notification");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pat_ID");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER")
                        .HasColumnName("round");

                    b.Property<decimal>("ServiceFee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("service_fee");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("service_ID");

                    b.Property<int?>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("staff_ID");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalFee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_fee");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StaffId");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Clinics.Entities.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("clinic_ID");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("clinic_address");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("clinic_email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("BLOB")
                        .HasColumnName("clinic_logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("clinic_name");

                    b.Property<string>("Phone1")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("clinic_phone1");

                    b.Property<string>("Phone2")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("clinic_phone2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("clinics", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.ClassRevenue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("class_rev_ID");

                    b.Property<decimal>("AmountDue")
                        .HasColumnType("TEXT")
                        .HasColumnName("amount_due");

                    b.Property<decimal>("AmountReceived")
                        .HasColumnType("TEXT")
                        .HasColumnName("amount_received");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FaterName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("student_fathername");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("student_firstname");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("invoice_ID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("student_lastname");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<DateOnly?>("RegisterDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("reg_date");

                    b.Property<string>("Subject")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("subject");

                    b.Property<string>("TeacherFullName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("teacher_fullname");

                    b.Property<decimal>("TotalFee")
                        .HasColumnType("TEXT")
                        .HasColumnName("total_fee");

                    b.HasKey("Id");

                    b.ToTable("class_revenues", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("exp_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("expense_name");

                    b.HasKey("Id");

                    b.ToTable("expenses", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.ExpenseDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("exp_detail_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpenseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("exp_ID");

                    b.Property<int?>("ExpenseInvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Inoice")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("item_name");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("purchase_date");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<string>("QuantityUnit")
                        .HasColumnType("TEXT")
                        .HasColumnName("qty_unit");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("purchased_by");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT")
                        .HasColumnName("total");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId");

                    b.HasIndex("ExpenseInvoiceId");

                    b.HasIndex("StaffId");

                    b.ToTable("expense_detail", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.ExpenseInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("exp_inv_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_by");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.ToTable("expense_invoices", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.FeePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("payment_ID");

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("apt_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DueAmount")
                        .HasColumnType("TEXT")
                        .HasColumnName("due_amount");

                    b.Property<int>("InstallmentCounter")
                        .HasColumnType("INTEGER")
                        .HasColumnName("installment_counter");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("TEXT")
                        .HasColumnName("paid_amount");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_date");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("staff_ID");

                    b.Property<int?>("TreatmentPlanId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tp_ID");

                    b.Property<decimal>("WholeFeePaid")
                        .HasColumnType("TEXT")
                        .HasColumnName("whole_fee_paid");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("StaffId");

                    b.HasIndex("TreatmentPlanId");

                    b.ToTable("fee_payments", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.TaxPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("payment_ID");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("paid_amount");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DuePaid")
                        .HasColumnType("TEXT")
                        .HasColumnName("due_paid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<int>("PaidBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("paid_by");

                    b.Property<DateOnly>("PaidDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("paid_date");

                    b.Property<int>("TaxesId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tax_ID");

                    b.HasKey("Id");

                    b.HasIndex("PaidBy");

                    b.HasIndex("TaxesId");

                    b.ToTable("tax_pay_ID", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.Taxes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("tax_ID");

                    b.Property<decimal>("AnnualIncome")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("annual_income");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TIN")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("TIN");

                    b.Property<decimal>("TaxForYear")
                        .HasColumnType("TEXT")
                        .HasColumnName("tax_for_year");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("TEXT")
                        .HasColumnName("tax_rate");

                    b.Property<decimal>("TotalAnnualTax")
                        .HasColumnType("TEXT")
                        .HasColumnName("total_annual_tax");

                    b.HasKey("Id");

                    b.ToTable("taxes", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Inventory.Entities.SupplyInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("supply_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("QtyInStock")
                        .HasColumnType("INTEGER")
                        .HasColumnName("qty_in_stock");

                    b.Property<DateOnly>("RegDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("reg_date");

                    b.Property<decimal?>("UnitPrice")
                        .HasMaxLength(50)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("supplies_inventory", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Inventory.Entities.SupplySale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ssale_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("patient_ID");

                    b.Property<decimal>("QuantitySold")
                        .HasColumnType("TEXT")
                        .HasColumnName("qty_sold");

                    b.Property<DateOnly>("SaleDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_date");

                    b.Property<int?>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("staff_ID");

                    b.Property<int?>("SupplyInventoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supply_ID");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("total_price");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("StaffId");

                    b.HasIndex("SupplyInventoryId");

                    b.ToTable("supplies_sales", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Labs.Entities.Lab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("lab_ID");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LabManager")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("lab_manager");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("lab_name");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone1");

                    b.Property<string>("Phone2")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("labs", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Labs.Entities.LabCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("case_ID");

                    b.Property<string>("CaseStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("case_status");

                    b.Property<int>("CaseType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("case_type");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateReceived")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_received");

                    b.Property<DateOnly>("DateSent")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_sent");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LabId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lab_ID");

                    b.Property<string>("Material")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("material");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("OtherServiceDetails")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("otherService_details");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("patient_ID");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("staff_ID");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("total_price");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("CaseType");

                    b.HasIndex("LabId");

                    b.HasIndex("PatientId");

                    b.HasIndex("StaffId");

                    b.ToTable("lab_cases", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Labs.Entities.LabPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("lab_payment_ID");

                    b.Property<decimal>("AmountDue")
                        .HasColumnType("TEXT")
                        .HasColumnName("amount_due");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("TEXT")
                        .HasColumnName("amount_paid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LabCaseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("case_ID");

                    b.Property<int>("LabId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lab_ID");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_date");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("payment_status");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("staff_ID");

                    b.HasKey("Id");

                    b.HasIndex("LabCaseId");

                    b.HasIndex("LabId");

                    b.HasIndex("StaffId");

                    b.ToTable("lab_payments", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Patients.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pat_ID");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER")
                        .HasColumnName("age");

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("blood_group");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerPatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cust_pat_ID");

                    b.Property<string>("FatherName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("fathername");

                    b.Property<string>("FileId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_ID");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("firstname");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("sex");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("lastname");

                    b.Property<string>("MaritalStatus")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("marital_status");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("BLOB")
                        .HasColumnName("photo");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("reg_date");

                    b.Property<string>("SponsorBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("sponsor_by");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("staff_ID");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("Phone");

                    b.HasIndex("StaffId");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Pharmacy.Entities.MedicineInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("med_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dosage")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("dosage");

                    b.Property<DateOnly?>("ExpireDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("expire_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("issue_date");

                    b.Property<string>("Name1")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("name1");

                    b.Property<string>("Name2")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name2");

                    b.Property<int>("QtyInStock")
                        .HasColumnType("INTEGER")
                        .HasColumnName("qty_in_stock");

                    b.Property<string>("Strength")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("strength");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<string>("notes")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.HasIndex("Name1")
                        .IsUnique();

                    b.ToTable("medicine_inventory", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Pharmacy.Entities.MedicineSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("msale_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedicineInventoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("med_ID");

                    b.Property<int?>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("patient_ID");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("qty_sold");

                    b.Property<DateOnly>("SaleDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_date");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("staff_ID");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("total_price");

                    b.HasKey("Id");

                    b.HasIndex("MedicineInventoryId");

                    b.HasIndex("PatientId");

                    b.HasIndex("StaffId");

                    b.ToTable("medicine_sales", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Staffs.Entities.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("staff_ID");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<byte[]>("ContractFile")
                        .HasColumnType("BLOB")
                        .HasColumnName("contract_file");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyPhone1")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("family_phone1");

                    b.Property<string>("FamilyPhone2")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("family_phone2");

                    b.Property<string>("FileType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_type");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("firstname");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("hire_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("lastname");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("BLOB")
                        .HasColumnName("photo");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("position");

                    b.Property<decimal?>("Prepayment")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("prepayment");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salary");

                    b.Property<string>("TazkiraId")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("tazkira_ID");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("TazkiraId")
                        .IsUnique();

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("condition_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("condition_name");

                    b.HasKey("Id");

                    b.ToTable("conditions", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.ConditionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("condition_detail_ID");

                    b.Property<int>("ConditionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("condition_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DaignosisDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("diagnosis_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pat_ID");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER")
                        .HasColumnName("result");

                    b.Property<string>("Severty")
                        .HasColumnType("TEXT")
                        .HasColumnName("severty");

                    b.Property<int>("TreatmentPlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConditionId");

                    b.HasIndex("PatientId");

                    b.HasIndex("TreatmentPlanId");

                    b.ToTable("condition_details", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.PatientService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("patient_service_ID");

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("apt_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pat_ID");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ser_ID");

                    b.Property<int>("ServiceRequirementId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("req_ID");

                    b.Property<int?>("TreatmentPlanId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tp_ID");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ServiceRequirementId");

                    b.HasIndex("TreatmentPlanId");

                    b.ToTable("patient_services", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.PlanService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ps_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ServiceFee")
                        .HasColumnType("TEXT")
                        .HasColumnName("service_fee");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("service_ID");

                    b.Property<decimal>("TotalFee")
                        .HasColumnType("TEXT")
                        .HasColumnName("total_fee");

                    b.Property<int>("TreatmentPlanId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tp_ID");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("TreatmentPlanId");

                    b.ToTable("plan_services", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.Retreatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("retreatment_ID");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("apt_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DamageServiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Damage_service_ID");

                    b.Property<int>("HelpServiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("help_service_ID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutcomeDetails")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("outcome_details");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pat_ID");

                    b.Property<string>("Reason")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<decimal>("RetreatmentCost")
                        .HasColumnType("TEXT")
                        .HasColumnName("retreatment_cost");

                    b.Property<DateOnly>("RetreatmentDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("retreatment_date");

                    b.Property<string>("RetreatmentOutcome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("retreatment_outcome");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("staff_ID");

                    b.Property<int>("TreatmentPlanId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tp_ID");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("DamageServiceId");

                    b.HasIndex("PatientId");

                    b.HasIndex("StaffId");

                    b.HasIndex("TreatmentPlanId");

                    b.ToTable("retreatments", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("service_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<decimal?>("Fee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fee");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("service_name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.ServiceRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("requirement_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequirmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("req_name");

                    b.HasKey("Id");

                    b.ToTable("service_requirements", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.TreatmentPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("tp_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<int>("Installments")
                        .HasColumnType("INTEGER")
                        .HasColumnName("installments");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Notification")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("notification");

                    b.Property<int?>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("patient_ID");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER")
                        .HasColumnName("round");

                    b.Property<int?>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("staff_ID");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalFee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_fee");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("StaffId");

                    b.ToTable("treatment_plans", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Xrays.Entities.PatientXray", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("xray_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pat_ID");

                    b.Property<DateOnly>("RegDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("reg_date");

                    b.Property<string>("XrayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("xray_name");

                    b.Property<string>("Xraytype")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("xray_type");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("patient_xrays", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DMS.Modules.Appointments.Entities.Appointment", b =>
                {
                    b.HasOne("DMS.Modules.Patients.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Treatments.Entities.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", "Staff")
                        .WithMany("Appointments")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Patient");

                    b.Navigation("Service");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.ExpenseDetail", b =>
                {
                    b.HasOne("DMS.Modules.Finances.Entities.Expense", "Expense")
                        .WithMany("ExpenseDetail")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Finances.Entities.ExpenseInvoice", null)
                        .WithMany("Details")
                        .HasForeignKey("ExpenseInvoiceId");

                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", "Staff")
                        .WithMany("ExpenseDetails")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expense");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.ExpenseInvoice", b =>
                {
                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", "Staff")
                        .WithMany("ExpenseInvoices")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.FeePayment", b =>
                {
                    b.HasOne("DMS.Modules.Appointments.Entities.Appointment", "Appointment")
                        .WithMany("FeePayments")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", "Staff")
                        .WithMany("FeePayments")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Treatments.Entities.TreatmentPlan", "TreatmentPlan")
                        .WithMany("FeePayments")
                        .HasForeignKey("TreatmentPlanId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Appointment");

                    b.Navigation("Staff");

                    b.Navigation("TreatmentPlan");
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.TaxPayment", b =>
                {
                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", "Staff")
                        .WithMany("TaxPayments")
                        .HasForeignKey("PaidBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Finances.Entities.Taxes", "Taxes")
                        .WithMany("TaxPayments")
                        .HasForeignKey("TaxesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("Taxes");
                });

            modelBuilder.Entity("DMS.Modules.Inventory.Entities.SupplySale", b =>
                {
                    b.HasOne("DMS.Modules.Patients.Entities.Patient", "Patient")
                        .WithMany("SupplySales")
                        .HasForeignKey("PatientId");

                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", "Staff")
                        .WithMany("SupplySales")
                        .HasForeignKey("StaffId");

                    b.HasOne("DMS.Modules.Inventory.Entities.SupplyInventory", "SupplyInventory")
                        .WithMany("Sales")
                        .HasForeignKey("SupplyInventoryId");

                    b.Navigation("Patient");

                    b.Navigation("Staff");

                    b.Navigation("SupplyInventory");
                });

            modelBuilder.Entity("DMS.Modules.Labs.Entities.LabCase", b =>
                {
                    b.HasOne("DMS.Modules.Treatments.Entities.Service", "Service")
                        .WithMany("LabCases")
                        .HasForeignKey("CaseType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Labs.Entities.Lab", "Lab")
                        .WithMany("LabCases")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Patients.Entities.Patient", "Patient")
                        .WithMany("LabCases")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", "Staff")
                        .WithMany("LabCases")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lab");

                    b.Navigation("Patient");

                    b.Navigation("Service");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DMS.Modules.Labs.Entities.LabPayment", b =>
                {
                    b.HasOne("DMS.Modules.Labs.Entities.LabCase", "LabCase")
                        .WithMany("Payments")
                        .HasForeignKey("LabCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Labs.Entities.Lab", "Lab")
                        .WithMany("Payments")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", "Staff")
                        .WithMany("Payments")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lab");

                    b.Navigation("LabCase");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DMS.Modules.Patients.Entities.Patient", b =>
                {
                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", "Staff")
                        .WithMany("Patients")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DMS.Modules.Pharmacy.Entities.MedicineSale", b =>
                {
                    b.HasOne("DMS.Modules.Pharmacy.Entities.MedicineInventory", "MedicineInventory")
                        .WithMany("Sales")
                        .HasForeignKey("MedicineInventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Patients.Entities.Patient", "Patient")
                        .WithMany("MedicineSales")
                        .HasForeignKey("PatientId");

                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", "Staff")
                        .WithMany("MedicineSales")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicineInventory");

                    b.Navigation("Patient");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.ConditionDetail", b =>
                {
                    b.HasOne("DMS.Modules.Treatments.Entities.Condition", "Condition")
                        .WithMany("ConditionDetails")
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Patients.Entities.Patient", "Patient")
                        .WithMany("ConditionDetails")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Treatments.Entities.TreatmentPlan", "TreatmentPlan")
                        .WithMany("ConditionDetails")
                        .HasForeignKey("TreatmentPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condition");

                    b.Navigation("Patient");

                    b.Navigation("TreatmentPlan");
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.PatientService", b =>
                {
                    b.HasOne("DMS.Modules.Appointments.Entities.Appointment", "Appointment")
                        .WithMany("PatientServices")
                        .HasForeignKey("AppointmentId");

                    b.HasOne("DMS.Modules.Patients.Entities.Patient", "Patient")
                        .WithMany("PatientServices")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Treatments.Entities.Service", "Service")
                        .WithMany("PatientServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Treatments.Entities.ServiceRequirement", "ServiceRequirement")
                        .WithMany("PatientServices")
                        .HasForeignKey("ServiceRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Treatments.Entities.TreatmentPlan", "TreatmentPlan")
                        .WithMany("PatientServices")
                        .HasForeignKey("TreatmentPlanId");

                    b.Navigation("Appointment");

                    b.Navigation("Patient");

                    b.Navigation("Service");

                    b.Navigation("ServiceRequirement");

                    b.Navigation("TreatmentPlan");
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.PlanService", b =>
                {
                    b.HasOne("DMS.Modules.Treatments.Entities.Service", "Service")
                        .WithMany("PlanServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Treatments.Entities.TreatmentPlan", "TreatmentPlan")
                        .WithMany("PlanServices")
                        .HasForeignKey("TreatmentPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("TreatmentPlan");
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.Retreatment", b =>
                {
                    b.HasOne("DMS.Modules.Appointments.Entities.Appointment", "Appointment")
                        .WithMany("Retreatments")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Treatments.Entities.Service", "Service")
                        .WithMany("Retreatments")
                        .HasForeignKey("DamageServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Patients.Entities.Patient", "Patient")
                        .WithMany("Retreatments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", "Staff")
                        .WithMany("Retreatments")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Treatments.Entities.TreatmentPlan", "TreatmentPlan")
                        .WithMany("Retreatments")
                        .HasForeignKey("TreatmentPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Patient");

                    b.Navigation("Service");

                    b.Navigation("Staff");

                    b.Navigation("TreatmentPlan");
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.TreatmentPlan", b =>
                {
                    b.HasOne("DMS.Modules.Patients.Entities.Patient", "Patient")
                        .WithMany("TreatmentPlans")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", "Staff")
                        .WithMany("TreatmentPlans")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Patient");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DMS.Modules.Xrays.Entities.PatientXray", b =>
                {
                    b.HasOne("DMS.Modules.Patients.Entities.Patient", "Patient")
                        .WithMany("PatientXrays")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DMS.Modules.Appointments.Entities.Appointment", b =>
                {
                    b.Navigation("FeePayments");

                    b.Navigation("PatientServices");

                    b.Navigation("Retreatments");
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.Expense", b =>
                {
                    b.Navigation("ExpenseDetail");
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.ExpenseInvoice", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.Taxes", b =>
                {
                    b.Navigation("TaxPayments");
                });

            modelBuilder.Entity("DMS.Modules.Inventory.Entities.SupplyInventory", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("DMS.Modules.Labs.Entities.Lab", b =>
                {
                    b.Navigation("LabCases");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DMS.Modules.Labs.Entities.LabCase", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DMS.Modules.Patients.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ConditionDetails");

                    b.Navigation("LabCases");

                    b.Navigation("MedicineSales");

                    b.Navigation("PatientServices");

                    b.Navigation("PatientXrays");

                    b.Navigation("Retreatments");

                    b.Navigation("SupplySales");

                    b.Navigation("TreatmentPlans");
                });

            modelBuilder.Entity("DMS.Modules.Pharmacy.Entities.MedicineInventory", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("DMS.Modules.Staffs.Entities.Staff", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ExpenseDetails");

                    b.Navigation("ExpenseInvoices");

                    b.Navigation("FeePayments");

                    b.Navigation("LabCases");

                    b.Navigation("MedicineSales");

                    b.Navigation("Patients");

                    b.Navigation("Payments");

                    b.Navigation("Retreatments");

                    b.Navigation("SupplySales");

                    b.Navigation("TaxPayments");

                    b.Navigation("TreatmentPlans");
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.Condition", b =>
                {
                    b.Navigation("ConditionDetails");
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.Service", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("LabCases");

                    b.Navigation("PatientServices");

                    b.Navigation("PlanServices");

                    b.Navigation("Retreatments");
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.ServiceRequirement", b =>
                {
                    b.Navigation("PatientServices");
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.TreatmentPlan", b =>
                {
                    b.Navigation("ConditionDetails");

                    b.Navigation("FeePayments");

                    b.Navigation("PatientServices");

                    b.Navigation("PlanServices");

                    b.Navigation("Retreatments");
                });
#pragma warning restore 612, 618
        }
    }
}
