// <auto-generated />
using System;
using DMS.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DMSAPI.Migrations
{
    [DbContext(typeof(DMSContext))]
    partial class DMSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("StaffId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Appointments.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("apt_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("details");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount");

                    b.Property<int>("Installment")
                        .HasColumnType("INTEGER")
                        .HasColumnName("installment");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MeetDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("meet_date");

                    b.Property<string>("Notification")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("notification");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pat_ID");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER")
                        .HasColumnName("round");

                    b.Property<decimal>("ServiceFee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("service_fee");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("service_ID");

                    b.Property<int?>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("staff_ID");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalFee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_fee");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StaffId");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Clinics.Entities.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("clinic_ID");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("clinic_address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("clinic_email");

                    b.Property<int?>("FounderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("clinic_founder");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("BLOB")
                        .HasColumnName("clinic_logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("clinic_name");

                    b.Property<string>("Phone1")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("clinic_phone1");

                    b.Property<string>("Phone2")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("clinic_phone2");

                    b.Property<int?>("StaffId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FounderId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StaffId");

                    b.ToTable("clinics", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.ClassRevenue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("class_ID");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("class_name");

                    b.HasKey("Id");

                    b.ToTable("class_revenues", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("expense_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("expense_name");

                    b.HasKey("Id");

                    b.ToTable("expenses", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.ExpenseDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("detail_ID");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("expense_date");

                    b.Property<int>("ExpenseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expense_ID");

                    b.Property<int?>("ExpenseInvoiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("invoice_ID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("staff_ID");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId");

                    b.HasIndex("ExpenseInvoiceId");

                    b.HasIndex("StaffId");

                    b.ToTable("expense_detail", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.ExpenseInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("invoice_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_no");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id");

                    b.ToTable("expense_invoices", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.FeePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("payment_ID");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("apt_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_type");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("reference_no");

                    b.Property<decimal>("Remaining")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("remaining");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("remarks");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("staff_ID");

                    b.Property<int?>("TreatmentPlanId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tp_ID");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("StaffId");

                    b.HasIndex("TreatmentPlanId");

                    b.ToTable("fee_payments", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.Tax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("tax_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("tax_name");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("percentage");

                    b.HasKey("Id");

                    b.ToTable("taxes", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.TaxPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("payment_ID");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_date");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("reference_no");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("remarks");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("staff_ID");

                    b.Property<int>("TaxId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tax_ID");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex("TaxId");

                    b.ToTable("tax_payments", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Inventory.Entities.SupplyInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("item_name");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("ReorderLevel")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("reorder_level");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("supplies_inventory", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Inventory.Entities.SupplySale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("sale_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pat_ID");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("qty");

                    b.Property<DateOnly>("SaleDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_date");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("staff_ID");

                    b.Property<int>("SupplyInventoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_ID");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("StaffId");

                    b.HasIndex("SupplyInventoryId");

                    b.ToTable("supplies_sales", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Labs.Entities.Lab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("lab_ID");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("lab_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("labs", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Labs.Entities.LabCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("case_ID");

                    b.Property<DateOnly>("CaseDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("case_date");

                    b.Property<string>("CaseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("case_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("delivery_date");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fee");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LabId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lab_ID");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pat_ID");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("LabId");

                    b.HasIndex("PatientId");

                    b.ToTable("lab_cases", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Labs.Entities.LabPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("payment_ID");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LabCaseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("case_ID");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_date");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("reference_no");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("remarks");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("staff_ID");

                    b.HasKey("Id");

                    b.HasIndex("LabCaseId");

                    b.HasIndex("StaffId");

                    b.ToTable("lab_payments", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Medicines.Entities.MedicineInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("medicine_ID");

                    b.Property<string>("Company")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("company");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ExpireDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("expire_date");

                    b.Property<string>("GenericName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("generic_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("medicine_name");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("quantity");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("medicine_inventory", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Medicines.Entities.MedicineSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("sale_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedicineInventoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("medicine_ID");

                    b.Property<int?>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pat_ID");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("qty");

                    b.Property<DateOnly>("SaleDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_date");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("staff_ID");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("MedicineInventoryId");

                    b.HasIndex("PatientId");

                    b.HasIndex("StaffId");

                    b.ToTable("medicine_sales", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Patients.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pat_ID");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER")
                        .HasColumnName("age");

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("blood_group");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerPatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cust_pat_ID");

                    b.Property<string>("FatherName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("fathername");

                    b.Property<string>("FileId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_ID");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("firstname");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("sex");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("lastname");

                    b.Property<string>("MaritalStatus")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("marital_status");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("BLOB")
                        .HasColumnName("photo");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("reg_date");

                    b.Property<string>("SponsorBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("sponsor_by");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("staff_ID");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("Phone");

                    b.HasIndex("StaffId");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Staffs.Entities.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("staff_ID");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<byte[]>("ContractFile")
                        .HasColumnType("BLOB")
                        .HasColumnName("contract_file");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyPhone1")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("family_phone1");

                    b.Property<string>("FamilyPhone2")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("family_phone2");

                    b.Property<string>("FileType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_type");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("firstname");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("hire_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("lastname");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("BLOB")
                        .HasColumnName("photo");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("position");

                    b.Property<decimal>("Prepayment")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("prepayment");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salary");

                    b.Property<string>("TazkiraId")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("tazkira_ID");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("TazkiraId")
                        .IsUnique();

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("condition_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("condition_name");

                    b.HasKey("Id");

                    b.ToTable("conditions", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.ConditionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("condition_detail_ID");

                    b.Property<DateOnly>("ConditionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("condition_date");

                    b.Property<int>("ConditionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("condition_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pat_ID");

                    b.Property<int>("ToothNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tooth_no");

                    b.HasKey("Id");

                    b.HasIndex("ConditionId");

                    b.HasIndex("PatientId");

                    b.ToTable("condition_details", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.PatientService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("patient_service_ID");

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("apt_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fee");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Paid")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("paid");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pat_ID");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("qty");

                    b.Property<decimal>("Remaining")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("remaining");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("service_date");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("service_ID");

                    b.Property<int?>("TreatmentPlanId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tp_ID");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("TreatmentPlanId");

                    b.ToTable("patient_services", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.PlanService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ps_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("qty");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("service_ID");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<int>("TreatmentPlanId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tp_ID");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("TreatmentPlanId");

                    b.ToTable("plan_services", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.Retreatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("retreatment_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pat_ID");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<DateOnly>("RetreatmentDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("retreatment_date");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("staff_ID");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("StaffId");

                    b.ToTable("retreatments", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("service_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fee");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("service_name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.ServiceRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("requirement_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("item_name");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("quantity");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("service_ID");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("service_requirements", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.TreatmentPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("tp_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<int>("Installments")
                        .HasColumnType("INTEGER")
                        .HasColumnName("installments");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Notification")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("notification");

                    b.Property<int?>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("patient_ID");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER")
                        .HasColumnName("round");

                    b.Property<int?>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("staff_ID");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalFee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_fee");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("StaffId");

                    b.ToTable("treatment_plans", (string)null);
                });

            modelBuilder.Entity("DMS.Modules.Xrays.Entities.PatientXray", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("xray_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT")
                        .HasColumnName("image");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("xray_name");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pat_ID");

                    b.Property<DateOnly>("XrayDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("xray_date");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("patient_xrays", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DMS.Modules.Appointments.Entities.Appointment", b =>
                {
                    b.HasOne("DMS.Modules.Patients.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Treatments.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Patient");

                    b.Navigation("Service");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DMS.Modules.Clinics.Entities.Clinic", b =>
                {
                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", "Founder")
                        .WithMany()
                        .HasForeignKey("FounderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", null)
                        .WithMany("Clinics")
                        .HasForeignKey("StaffId");

                    b.Navigation("Founder");
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.ExpenseDetail", b =>
                {
                    b.HasOne("DMS.Modules.Finances.Entities.Expense", "Expense")
                        .WithMany("Details")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Finances.Entities.ExpenseInvoice", "ExpenseInvoice")
                        .WithMany("Details")
                        .HasForeignKey("ExpenseInvoiceId");

                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expense");

                    b.Navigation("ExpenseInvoice");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.FeePayment", b =>
                {
                    b.HasOne("DMS.Modules.Appointments.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Treatments.Entities.TreatmentPlan", "TreatmentPlan")
                        .WithMany()
                        .HasForeignKey("TreatmentPlanId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Appointment");

                    b.Navigation("Staff");

                    b.Navigation("TreatmentPlan");
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.TaxPayment", b =>
                {
                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Finances.Entities.Tax", "Tax")
                        .WithMany("Payments")
                        .HasForeignKey("TaxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("Tax");
                });

            modelBuilder.Entity("DMS.Modules.Inventory.Entities.SupplySale", b =>
                {
                    b.HasOne("DMS.Modules.Patients.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId");

                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Inventory.Entities.SupplyInventory", "SupplyInventory")
                        .WithMany("Sales")
                        .HasForeignKey("SupplyInventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Staff");

                    b.Navigation("SupplyInventory");
                });

            modelBuilder.Entity("DMS.Modules.Labs.Entities.LabCase", b =>
                {
                    b.HasOne("DMS.Modules.Labs.Entities.Lab", "Lab")
                        .WithMany("LabCases")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Patients.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lab");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DMS.Modules.Labs.Entities.LabPayment", b =>
                {
                    b.HasOne("DMS.Modules.Labs.Entities.LabCase", "LabCase")
                        .WithMany("Payments")
                        .HasForeignKey("LabCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LabCase");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DMS.Modules.Medicines.Entities.MedicineSale", b =>
                {
                    b.HasOne("DMS.Modules.Medicines.Entities.MedicineInventory", "MedicineInventory")
                        .WithMany("Sales")
                        .HasForeignKey("MedicineInventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Patients.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId");

                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicineInventory");

                    b.Navigation("Patient");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DMS.Modules.Patients.Entities.Patient", b =>
                {
                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.ConditionDetail", b =>
                {
                    b.HasOne("DMS.Modules.Treatments.Entities.Condition", "Condition")
                        .WithMany("ConditionDetails")
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Patients.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condition");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.PatientService", b =>
                {
                    b.HasOne("DMS.Modules.Appointments.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId");

                    b.HasOne("DMS.Modules.Patients.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Treatments.Entities.Service", "Service")
                        .WithMany("PatientServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Treatments.Entities.TreatmentPlan", "TreatmentPlan")
                        .WithMany()
                        .HasForeignKey("TreatmentPlanId");

                    b.Navigation("Appointment");

                    b.Navigation("Patient");

                    b.Navigation("Service");

                    b.Navigation("TreatmentPlan");
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.PlanService", b =>
                {
                    b.HasOne("DMS.Modules.Treatments.Entities.Service", "Service")
                        .WithMany("PlanServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Treatments.Entities.TreatmentPlan", "TreatmentPlan")
                        .WithMany()
                        .HasForeignKey("TreatmentPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("TreatmentPlan");
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.Retreatment", b =>
                {
                    b.HasOne("DMS.Modules.Patients.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.ServiceRequirement", b =>
                {
                    b.HasOne("DMS.Modules.Treatments.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.TreatmentPlan", b =>
                {
                    b.HasOne("DMS.Modules.Patients.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DMS.Modules.Staffs.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Patient");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DMS.Modules.Xrays.Entities.PatientXray", b =>
                {
                    b.HasOne("DMS.Modules.Patients.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.Expense", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.ExpenseInvoice", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("DMS.Modules.Finances.Entities.Tax", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DMS.Modules.Inventory.Entities.SupplyInventory", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("DMS.Modules.Labs.Entities.Lab", b =>
                {
                    b.Navigation("LabCases");
                });

            modelBuilder.Entity("DMS.Modules.Labs.Entities.LabCase", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DMS.Modules.Medicines.Entities.MedicineInventory", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("DMS.Modules.Staffs.Entities.Staff", b =>
                {
                    b.Navigation("Clinics");
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.Condition", b =>
                {
                    b.Navigation("ConditionDetails");
                });

            modelBuilder.Entity("DMS.Modules.Treatments.Entities.Service", b =>
                {
                    b.Navigation("PatientServices");

                    b.Navigation("PlanServices");
                });
#pragma warning restore 612, 618
        }
    }
}
